services:
  db:
    image: postgres:16
    container_name: postgres_dev
    environment:
      POSTGRES_DB: db_2
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - phoenix_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db_2"]
      interval: 10s
      timeout: 5s
      retries: 5

  phoenix:
    image: arizephoenix/phoenix:latest
    container_name: phoenix_dev
    ports:
      - "6006:6006"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PHOENIX_WORKING_DIR=/mnt/data
      - PHOENIX_ENABLE_AUTH=True
      - PHOENIX_SECRET=phoenix_secret1phoenix_secret1phoenix_secret
      - PHOENIX_DB_HOST=db
      - PHOENIX_DB_PORT=5432
      - PHOENIX_DB_USER=user
      - PHOENIX_DB_PASSWORD=password
      - PHOENIX_DB_NAME=db_2
    volumes:
      - phoenix_data:/mnt/data

volumes:
  phoenix_data:
  phoenix_db_data: